name = "GCIdentifier"
uuid = "b7ea765e-cbac-4e4a-9b0d-5427cc302506"
authors = ["Hon Wa Yew <yewhonwa@gmail.com>", "Pierre Walker <pwalker@mit.edu>", "Andrés Riedemann <andres.riedemann@gmail.com>"]
version = "0.1.0"

[deps]
ChemicalIdentifiers = "fa4ea961-1416-484e-bda2-883ee1634ba5"
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
RDKitMinimalLib = "44044271-7623-48dc-8250-42433c44e4b7"

[weakdeps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
ChemicalIdentifiers = "fa4ea961-1416-484e-bda2-883ee1634ba5"

[extensions]
GCIdentifierClapeyronExt = "Clapeyron"
GCIdentifierChemicalIdentifiersExt = "ChemicalIdentifiers"

[compat]
Clapeyron = "0.4"


[extras]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]