const EPPR78Groups = [GCPair(raw"[CX4H3]", "CH3"),
GCPair(raw"[!R;CX4H2]", "CH2"),
GCPair(raw"[!R;CX4H]", "CH"),
GCPair(raw"[!R;CX4H0]", "C"),
GCPair(raw"[CH4]","CH4"),
GCPair(raw"CC", "C2H6"),
GCPair(raw"[cH]","CH aro"),
GCPair(raw"[c]","C aro"),
GCPair(raw"[cR2]", "C fused aromatic rings"),
GCPair(raw"[CH2;R]","CH2 cyclic"),
GCPair(raw"[CH2R]", "CH cyclic"),
GCPair(raw"[CHR]", "C cyclic"),
GCPair(raw"[C;X2](=O)(=O)","CO2"),
GCPair(raw"N#N", "N2"),
GCPair(raw"S", "H2S"),
GCPair(raw"[SX2;H1;!R]", "SH"),
GCPair(raw"[OH2]","H2O"),
GCPair(raw"C=C", "C2H4"),
GCPair(raw"[CX3H2]","CH2 alkenic"),
GCPair(raw"[!R;CX3H1;!$([CX3H1](=O))]","CH alkenic"),
GCPair(raw"[C;!R;H0;$(C=[C])]","C alkenic"),
GCPair(raw"[C;R;H1;$(C=[C])]", "CH cycloalkenic"),
GCPair(raw"[C;R;H0;$(C=[C])]", "C cycloalkenic"),
GCPair(raw"[H][H]", "H2"),
GCPair(raw"FC(F)(F)C(F)(F)F", "C2F6"),
GCPair(raw"C(F)(F)F","CF3"),
GCPair(raw"[$([C](-[F])(-[F])-C)]", "CF2"),
GCPair(raw"[CX3;H0](=[C])[F][F]", "CF2 double bond"),
GCPair(raw"[CX3;H0](=[C])[F]", "CF double bond"),
GCPair(raw"FC(F)C", "C2H4F2"),
GCPair(raw"FCC(F)(F)F", "C2H2F4"),
GCPair(raw"[C-]#[O+]", "CO"),
GCPair(raw"[He]", "He"),
GCPair(raw"[Ar]", "Ar"),
GCPair(raw"O=S=O", "SO2"),
GCPair(raw"O=O", "O2"),
GCPair(raw"[N]=O", "NO"),
GCPair(raw"O=C=S", "COS"),
GCPair(raw"N", "NH3"),
GCPair(raw"N(=O)[O]", "NO2"),
GCPair(raw"[O-][N+](=O)[N+]([O-])=O", "N2O4"),
GCPair(raw"N#[N+][O-]", "N2O"),
GCPair(raw"C#C", "C2H2"),
GCPair(raw"[CX2;H1]#[CX2;H0]","HC=-C-"),
GCPair(raw"[CX2;H0]#[CX2;H0]","-C=-C-"),]

export EPPR78Groups