const JobackGroups = [GCPair(raw"[CX4H3]","-CH3"),
GCPair(raw"[!R;CX4H2]","-CH2-"),
GCPair(raw"[!R;CX4H]",">CH-"),
GCPair(raw"[!R;CX4H0]",">C<"),
GCPair(raw"[CX3H2][CX3H1]","CH2=CH-"),
GCPair(raw"[CX3H1][CX3H1]","-CH=CH-"),
GCPair(raw"[$([!R;#6X3H0]);!$([!R;#6X3H0]=[#8])]","=C<"),
GCPair(raw"[$([CX2H0](=*)=*)]","=C="),
GCPair(raw"[$([CX2H1]#[!#7])]","CH"),
GCPair(raw"[$([CX2H0]#[!#7])]","C"),
GCPair(raw"[R;CX4H2]","ring-CH2-"),
GCPair(raw"[R;CX4H]","ring>CH-"),
GCPair(raw"[R;CX4H0]","ring>C<"),
GCPair(raw"[R;CX3H1,cX3H1]","ring=CH-"),
GCPair(raw"[$([R;#6X3H0]);!$([R;#6X3H0]=[#8])]","ring=C<"),
GCPair(raw"[F]","-F"),
GCPair(raw"[Cl]","-Cl"),
GCPair(raw"[Br]","-Br"),
GCPair(raw"[I]","-I"),
GCPair(raw"[OX2H;!$([OX2H]-[#6]=[O]);!$([OX2H]-a)]","-OH (alcohol)"),
GCPair(raw"[O;H1;$(O-!@c)]","-OH (phenol)"),
GCPair(raw"[OX2H0;!R;!$([OX2H0]-[#6]=[#8])]","-O- (non-ring)"),
GCPair(raw"[#8X2H0;R;!$([#8X2H0]~[#6]=[#8])]","-O- (ring)"),
GCPair(raw"[$([CX3H0](=[OX1]));!$([CX3](=[OX1])-[OX2]);!R]=O",">C=O (non-ring)"),
GCPair(raw"[$([#6X3H0](=[OX1]));!$([#6X3](=[#8X1])~[#8X2]);R]=O",">C=O (ring)"),
GCPair(raw"[CH;D2](=O)","O=CH- (aldehyde)"),
GCPair(raw"[OX2H]-[C]=O","-COOH (acid)"),
GCPair(raw"[#6X3H0;!$([#6X3H0](~O)(~O)(~O))](=[#8X1])[#8X2H0]","-COO- (ester)"),
GCPair(raw"[OX1H0;!$([OX1H0]~[#6X3]);!$([OX1H0]~[#7X3]~[#8])]","=O (other than above)"),
GCPair(raw"[NX3H2]","-NH2"),
GCPair(raw"[NX3H1;!R]",">NH (non-ring)"),
GCPair(raw"[#7X3H1;R]",">NH (ring)"),
GCPair(raw"[#7X3H0;!$([#7](~O)~O)]",">N- (non-ring)"),
GCPair(raw"[#7X2H0;!R]","-N= (non-ring)"),
GCPair(raw"[#7X2H0;R]","-N= (ring)"),
GCPair(raw"[#7X2H1]","=NH"),
GCPair(raw"[#6X2]#[#7X1H0]","-CN"),
GCPair(raw"[$([#7X3,#7X3+][!#8])](=[O])~[O-]","-NO2"),
GCPair(raw"[SX2H]","-SH"),
GCPair(raw"[#16X2H0;!R]","-S- (non-ring)"),
GCPair(raw"[#16X2H0;R]","-S- (ring)")
]

export JobackGroups