const ogUNIFACGroups = [GCPair(raw"[CX4;H3;!R]","CH3"),
GCPair(raw"[CX4;H2;!R]","CH2"),
GCPair(raw"[CX4;H1;!R]","CH"),
GCPair(raw"[CX4;H0;!R]","C"),
GCPair(raw"[CX3;H2]=[CX3;H1]","CH2=CH"),
GCPair(raw"[CX3;H1]=[CX3;H1]","CH=CH"),
GCPair(raw"[CX3;H2]=[CX3;H0]","CH2=C"),
GCPair(raw"[CX3;H1]=[CX3;H0]","CH=C"),
GCPair(raw"[cX3;H1]","ACH"),
GCPair(raw"[cX3;H0]","AC"),
GCPair(raw"[cX3;H0][CX4;H3]","ACCH3"),
GCPair(raw"[cX3;H0][CX4;H2]","ACCH2"),
GCPair(raw"[cX3;H0][CX4;H1]","ACCH"),
GCPair(raw"[OH1;$([OH1][CX4H2])]","OH"), #OH (P)
GCPair(raw"[CX4;H3][OX2;H1]","CH3OH"),
GCPair(raw"[OH2]","H2O"),
GCPair(raw"[cX3;H0;R][OX2;H1]","ACOH"),
GCPair(raw"[CX4;H3][CX3](=O)","CH3CO"),
GCPair(raw"[CX4;H2][CX3](=O)","CH2CO"),
GCPair(raw"[CX3H1](=O)","CHO"),
GCPair(raw"[CH3][CX3;H0](=[O])[O]","CH3COO"),
GCPair(raw"[CX4;H2][CX3](=[OX1])[OX2]","CH2COO"),
GCPair(raw"[CX3;H1](=[OX1])[OX2]","HCOO"),
GCPair(raw"[CH3;!R][OH0;!R]","CH3O"),
GCPair(raw"[CH2;!R][OH0;!R]","CH2O"),
GCPair(raw"[C;H1;!R][OH0;!R]","CHO"),
GCPair(raw"[CX3H1](=O)","HCO"),
GCPair(raw"[CX4;H2;R][OX2;R][CX4;H2;R]","THF"),
GCPair(raw"[CX4;H3][NX3;H2]","CH3NH2"),
GCPair(raw"[CX4;H2][NX3;H2]","CH2NH2"),
GCPair(raw"[CX4;H1][NX3;H2]","CHNH2"),
GCPair(raw"[CX4;H3][NX3;H1]","CH3NH"),
GCPair(raw"[CX4;H2][NX3;H1]","CH2NH"),
GCPair(raw"[CX4;H1][NX3;H1]","CHNH"),
GCPair(raw"[CX4;H3][NX3;H0]","CH3N"),
GCPair(raw"[CX4;H2][NX3;H0]","CH2N"),
GCPair(raw"[c][NX3;H2]","ACNH2"),
GCPair(raw"[cX3H1][n][cX3H1]","AC2H2N"),
GCPair(raw"[cX3H0][n][cX3H1]","AC2HN"),
GCPair(raw"[cX3H0][n][cX3H0]","AC2N"),
GCPair(raw"[CX4;H3][CX2]#[NX1]","CH3CN"),
GCPair(raw"[CX4;H2][CX2]#[NX1]","CH2CN"),
GCPair(raw"[CX3,cX3](=[OX1])[OX2H0,oX2H0]","COO"),
GCPair(raw"[CX3](=[OX1])[O;H1]","COOH"),
GCPair(raw"[CX3;H1](=[OX1])[OX2;H1]","HCOOH"),
GCPair(raw"[CX4;H2;!$(C(Cl)(Cl))](Cl)","CH2CL"),
GCPair(raw"[CX4;H1;!$(C(Cl)(Cl))](Cl)","CHCL"),
GCPair(raw"[CX4;H0](Cl)","CCL"),
GCPair(raw"[CX4;H2;!$(C(Cl)(Cl)(Cl))](Cl)(Cl)","CH2CL2"),
GCPair(raw"[CX4;H1;!$(C(Cl)(Cl)(Cl))](Cl)(Cl)","CHCL2"),
GCPair(raw"[CX4;H0;!$(C(Cl)(Cl)(Cl))](Cl)(Cl)","CCL2"),
GCPair(raw"[CX4;H1;!$([CX4;H0](Cl)(Cl)(Cl)(Cl))](Cl)(Cl)(Cl)","CHCL3"),
GCPair(raw"[CX4;H0;!$([CX4;H0](Cl)(Cl)(Cl)(Cl))](Cl)(Cl)(Cl)","CCL3"),
GCPair(raw"[CX4;H0]([Cl])([Cl])([Cl])([Cl])","CCL4"),
GCPair(raw"[c][Cl]","ACCL"),
GCPair(raw"[CX4;H3][NX3](=[OX1])([OX1])","CH3NO2"),
GCPair(raw"[CX4;H2][NX3](=[OX1])([OX1])","CH2NO2"),
GCPair(raw"[CX4;H1][NX3](=[OX1])([OX1])","CHNO2"),
GCPair(raw"[cX3][NX3](=[OX1])([OX1])","ACNO2"),
GCPair(raw"C(=S)=S","CS2"),
GCPair(raw"[SX2H][CX4;H3]","CH3SH"),
GCPair(raw"[SX2H][CX4;H2]","CH2SH"),
GCPair(raw"c1cc(oc1)C=O","FURFURAL"),
GCPair(raw"[OX2;H1][CX4;H2][CX4;H2][OX2;H1]","DOH"),
GCPair(raw"[I]","I"),
GCPair(raw"[Br]","BR"),
GCPair(raw"[CX2;H1]#[CX2;H0]","CH=-C"),
GCPair(raw"[CX2;H0]#[CX2;H0]","C=-C"),
GCPair(raw"[SX3H0](=[OX1])([CX4;H3])[CX4;H3]","DMSO"),
GCPair(raw"[CX3;H2]=[CX3;H1][CX2;H0]#[NX1;H0]","ACRY"),
GCPair(raw"[$([Cl;H0]([C]=[C]))]","CL-(C=C)"),
GCPair(raw"[CX3;H0]=[CX3;H0]","C=C"),
GCPair(raw"[cX3][F]","ACF"),
GCPair(raw"[CX4;H3][N]([CX4;H3])[CX3;H1]=[O]","DMF"),
GCPair(raw"[NX3]([CX4;H2])([CX4;H2])[CX3;H1](=[OX1])","HCON(.."),
GCPair(raw"C(F)(F)F","CF3"),
GCPair(raw"C(F)F","CF2"),
GCPair(raw"C(F)","CF"),
GCPair(raw"[OH1;$([OH1][CX4H1])]","OH"), #OH (S)
GCPair(raw"[OH1;$([OH1][CX4H0])]","OH"), #OH (T)
GCPair(raw"[CX4H2;R][OX2;R]","TRIOXAN"),
GCPair(raw"[CX4H0][NH2]","CNH2"),
GCPair(raw"[OX1H0]=[C;R][NX3H0;R][CH3]","NMP"),
GCPair(raw"[OX1H0]=[CH0X3;R][H0;R][CH2]","NEP"),
GCPair(raw"[OX1H0;!R]=[CX3H0;R][NX3H0;R][C;!R]","NIPP"),
GCPair(raw"[OX1H0;!R]=[CH0X3;R][NX3H0;R][CH0;!R]","NTBP"),
GCPair(raw"[CX3H0](=[OX1H0])[NX3H2]","CONH2"),
GCPair(raw"[OX1H0;!R]=[CX3H0;!R][NH1X3;!R][CH3;!R]","CONHCH3"),
GCPair(raw"[CH2X4;!R][NH1X3;!R][CX3H0;!R]=[OX1H0;!R]","CONHCH2"),
GCPair(raw"[CX4H0](Cl)(Cl)(Cl)F","CCL3F"),
GCPair(raw"[CX4H0](Cl)(Cl)(F)F","CCL2F2"),
GCPair(raw"[CX4H0](Cl)(F)(F)F","CCLF3"),
GCPair(raw"[CX4H0](Cl)(Cl)(F)[#6]","CCL2F"),
GCPair(raw"[CX4H0](Cl)(F)(F)[#6]","CCLF2"),
GCPair(raw"[CX4H1](Cl)(Cl)F","HCCL2F"),
GCPair(raw"[CX4H1](Cl)(F)F","HCCLF2"),
GCPair(raw"[CX4H1](Cl)(F)[#6]","HCCLF"),
GCPair(raw"[CX4;H3;!R][SX2;H0]","CH3S"),
GCPair(raw"[CX4;H2;!R][SX2;H0]","CH2S"),
GCPair(raw"[CX4;H1;!R][SX2;H0]","CHS"),
GCPair(raw"[NX2H0]=[CX2H0]=[OX1]","NCO"),
GCPair(raw"[SiX4H3]","SIH3"),
GCPair(raw"[SiX4H2;!$([SiX4H2]O)]","SIH2"),
GCPair(raw"[SiX4H1;!$([SiX4H1]O)]","SIH"),
GCPair(raw"[SiX4H0;!$([SiX4H0]O)]","SI"),
GCPair(raw"[SiX4H2]O","SIH2O"),
GCPair(raw"[SiX4H1]O","SIHO"),
GCPair(raw"[SiX4H0]O","SIO"),
GCPair(raw"[CX3H0](=[OX1])[NX3H0]([CX4H3])[CX4H3]","CON(CH3)2"),
GCPair(raw"[CX3H0](=[OX1])[NX3H0]([CX4H2])[CX4H2]","CON(CH2)2"),
GCPair(raw"[CX3H0](=[OX1])[NX3H0]([CX4H3])[CX4H2]","CONCH3CH2"),
GCPair(raw"[NX3;R]1[CH2;R][CH2;R][OX2;R][CH2;R][CH2;R]1","MORPH"),
GCPair(raw"[nH]1[cH][n][cH][cH]1","IMIDAZOL"),
GCPair(raw"[n]1[cH][cH][cH][cH][cH]1","C5H5N"),
GCPair(raw"[n]1[cH][cH][cH][cH][c]1","C5H4N"),
# guess (di-substituted pyridine ring; may not reliably match, see notes): verify
GCPair(raw"[n]1[cH][cH][cH][c][c]1","C5H3N"),
# guess (thiophene alpha-position proxy, beta substitution not distinguished): verify
GCPair(raw"[cH][s][cH]","C4H4S"),
# guess (thiophene alpha-position proxy, beta substitution not distinguished): verify
GCPair(raw"[cH][s][c;H0]","C4H3S"),
# guess (thiophene alpha-position proxy, beta substitution not distinguished): verify
GCPair(raw"[c;H0][s][c;H0]","C4H2S"),
# guess (sulfolane-type ring CH2 alpha to sulfone S): verify
GCPair(raw"[CH2;R][SX4;R](=O)(=O)","(CH2)2SU"),
# guess (open-chain sulfone CH2-SO2-CH fragment): verify
GCPair(raw"[CX4H2][SX4](=O)(=O)[CX4H1]","CH2CHSU"),
# guess (bis(trifluoromethylsulfonyl)imide anion): verify
GCPair(raw"[N-]([SX4](=O)(=O)C(F)(F)F)[SX4](=O)(=O)C(F)(F)F","BTI")]

export ogUNIFACGroups